server:
  port: 29090

system:
  appId: bmmp-app
  token: bWlubGlhCg==
  security:
    jwt:
      tokenExpirationTime: 5 # Number of minutes
      refreshTokenExpTime: 1440 # Minutes
      tokenIssuer: http://minlia.com
      #      tokenSigningKey: minlia8EV6Hy5RMFK4EEACIDAwQus
      tokenSigningKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCizv54kvLWOVtVa5VDOXREg6yo
  sms:
    type: opt
    otp:
      url: https://10.15.102.13:8443/api/v1/sms
      x-jetco-client-id: efebe93a53cfe4f3b560b68fea87c6bb
      x-jetco-client-secret: 8b76a43e2369e1db8c93589360529443
      default-icc: 00852
      ssl-certificate-verification: false
      cert-path: F:\cert\bmp\jssecacerts
      store-password: 11111

# SPRING PROFILES
spring:
  profile: docker
  aop:
    auto: true
  application:
    name: BMP
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
    multipart:
      enabled: true
      max-file-size: 30MB  #(这里是限制的文件大小)
      max-request-size: 30MB #(这里是限制的文件大小)
  main:
    sources:
  mail:
    host: smtp.tidetech.com.hk
    port: 25
    username: dev-no-reply@tidetech.com.hk
    password: Dev@20190531
    properties.mail.smtp:
      auth: true
      ssl:
        enable: false
      starttls:
        enable: false
        required: false
  shardingsphere:
    datasource:
      names: ds
      ds:
        #        driver-class-code: com.mysql.jdbc.Driver
        #        url: jdbc:mysql://192.168.196.244:13306/bmp?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&allowMultiQueries=true
        driver-class-name: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://192.168.196.196:13306/bmptest?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&allowMultiQueries=true
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        initial-size: 1
        min-idle: 5
        max-active: 200
        max-total: 100
        max-wait: 60000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        #        max-evictable-idle-time-millis: 3600000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        log-abandoned: false
        remove-abandoned: false
        remove-abandoned-timeout-millis: 1800000
        use-global-data-source-stat: true
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        async-init: true
        filters: stat,slf4j,wall
    sharding:
      tables:
        bmp_application_info:
          actual-data-nodes: ds.bmp_application_info_${20190623..20190624}
          table-strategy:
            standard:
              range-algorithm-class-name: com.minlia.bmp.common.shardingsphere.algorithm.RangeApplicationNumberShardingAlgorithm
              sharding-column: number
              precise-algorithm-class-name: com.minlia.bmp.common.shardingsphere.algorithm.PreciseApplicationNumberShardingTableAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
        bmp_application_loan_info:
          actual-data-nodes: ds.bmp_application_loan_info_${20190623..20190624}
          table-strategy:
            standard:
              sharding-column: number
              precise-algorithm-class-name: com.minlia.bmp.common.shardingsphere.algorithm.PreciseApplicationNumberShardingTableAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
        bmp_application_personal_info:
          actual-data-nodes: ds.bmp_application_personal_info_${20190623..20190624}
          table-strategy:
            standard:
              sharding-column: number
              precise-algorithm-class-name: com.minlia.bmp.common.shardingsphere.algorithm.PreciseApplicationNumberShardingTableAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
        bmp_application_personal_info_others:
          actual-data-nodes: ds.bmp_application_personal_info_others_${20190623..20190624}
          table-strategy:
            standard:
              sharding-column: number
              precise-algorithm-class-name: com.minlia.bmp.common.shardingsphere.algorithm.PreciseApplicationNumberShardingTableAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
        bmp_application_company_info:
          actual-data-nodes: ds.bmp_application_company_info_${20190623..20190624}
          table-strategy:
            standard:
              sharding-column: number
              precise-algorithm-class-name: com.minlia.bmp.common.shardingsphere.algorithm.PreciseApplicationNumberShardingTableAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
        bmp_application_business_info:
          actual-data-nodes: ds.bmp_application_business_info_${20190623..20190624}
          table-strategy:
            standard:
              sharding-column: number
              precise-algorithm-class-name: com.minlia.bmp.common.shardingsphere.algorithm.PreciseApplicationNumberShardingTableAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
        bmp_application_business_guarantor_info:
          actual-data-nodes: ds.bmp_application_business_guarantor_info_${20190623..20190624}
          table-strategy:
            standard:
              sharding-column: number
              precise-algorithm-class-name: com.minlia.bmp.common.shardingsphere.algorithm.PreciseApplicationNumberShardingTableAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
        bmp_application_offer:
          actual-data-nodes: ds.bmp_application_offer_${20190623..20190624}
          table-strategy:
            standard:
              sharding-column: number
              precise-algorithm-class-name: com.minlia.bmp.common.shardingsphere.algorithm.PreciseApplicationNumberShardingTableAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
    props:
      executor:
        size: 200   #工作线程数量最大，默认值: 无限制
      sql:
        show: true  #是否开启SQL显示，默认值: false

mybatis:
  #    config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

swagger:
  title: ${spring.application.name}接口
  description: ${spring.application.name}接口
  version: 1.0
  contact: cloud@minlia.com
  path: /api/.*
  redirect: true

encrypt:
  body:
    aes-key: 12345678 #AES加密秘钥
    des-key: 12345678 #DES加密秘钥
    rsa-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs02q0YdzYndJXqvr+DiFwfeQ+VSXSz3yj6vlCmvcorkKs0qIchDNd20/xY12a8hh2p8HkAt8lTL0qpC+dDahMJk8OIoeSltAHPwneUMu6EdeG5F5HNBQfuzFcFDEjZFI2mdUMsSFZqyw5HlNGF12YPNbOrR5FTiRcTRUgzlvcXM1gDDwbxpZY3rNZpoXvIwpsKMrlB+DTkn9802Qwrs07u+UCaCCqxnAQGmCiGwKbha/jQTa/1Y5aTtC9Zn+RPjvjZ+M03GZfin3u0rhLRGNJfcRsDd5zcdsZwsf8fId+TpcuHOOUvvkcLT/WEL5I5TQV0o2AR41BNW2cGOxFL+0xwIDAQAB
    rsa-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCzTarRh3Nid0leq+v4OIXB95D5VJdLPfKPq+UKa9yiuQqzSohyEM13bT/FjXZryGHanweQC3yVMvSqkL50NqEwmTw4ih5KW0Ac/Cd5Qy7oR14bkXkc0FB+7MVwUMSNkUjaZ1QyxIVmrLDkeU0YXXZg81s6tHkVOJFxNFSDOW9xczWAMPBvGlljes1mmhe8jCmwoyuUH4NOSf3zTZDCuzTu75QJoIKrGcBAaYKIbApuFr+NBNr/VjlpO0L1mf5E+O+Nn4zTcZl+Kfe7SuEtEY0l9xGwN3nNx2xnCx/x8h35Oly4c45S++RwtP9YQvkjlNBXSjYBHjUE1bZwY7EUv7THAgMBAAECggEAQHjD3DV1Ism7owP0hDtmtRkcktp80DxFFK39XGLuYcBhfZhmOYWbK78nuBQmqZjSvraCFKRctpUs7ou/P7BJA12GDtpzC8+F3SY511t16WWIDCehwd+RoiHm2HziP/kmlgmjd+G8CfA8ZtrLAuDQaQn4GsK76wp9GZR0cv7a+JKW0LyaTDidTx8fYGsKHV4odps/erR08SBBs5rUETRXcJpGktOUe7k7YlNHCJf+Y1W5yKKehWvTh71veayhjBzxv9RqR0fVgnJDUMVEPATaTj1pVKyZgA/9oia9m8yXAnCVR6GutH0P1FisFijnAN1CpVbHeKhUy1KLZeemGG0zgQKBgQDqQRg9HBwfAHbzWE2NLRcCPIl5UOimYFeRRSBY+7DfDZFCu/jfmgh4mhrlJzDkny7dAJGtfSSM+ozppahuDB6uZjWHrbKZu2WG0qQwWojDAKsfY/TbsWlFm+TLhfALsFnSlVbTpUWqcG6/B/Jdd07ieccGFwTfLNCFdH6b64vDBwKBgQDD8rMHKQcvTEXdQTZGqJ1crTwqXuU3XMOau4h27VR7snDe4xpwl1rsP5W5SiraP5/9EtPwGKwjnEPUSWRHvj2wtBs/SB4A1VBdzKY+yM98eFzSf9HJZRra42SlU/Fw/jHKkRAUkp7gluc5DwZi7JfuxXS1RVgfMWbsTLKT8udQQQKBgQDlPUqBEu8aD5RYU0OhMkzf7WoDBICHwKQxD1q2eaf+wAI1Mko8VzqO+w/yzEV2laiAsbvd8SdBpzcatvh6qPWlaXRdEEhFVTPnml7+yronSpIrp9/I1nbUndhqquncJnngMDDF8WiZgGmAHEC74rOZwd5YQVKNLAfrcbMs1nbxJQKBgQC3SfOq8/bTiF4lq5VQnPKtuSH5ZFC265/QwjDRRgjruCuaYgbeYMXdDVFJRBY3lqJaAN2czgdfPBG6pngWH97mxmJiXFwsXVzSkNbFDeP/wzrYcFXVNCzdqS0A9Td4gV4j5HONOuVAogdhuSs5J6Sq5arY0Sev7e8fhFLaz7ENwQKBgQDjRRfpDUqxeZNjjx0Huu5EFe776ATLxhXHJT7xT7+NXKQK+SwzGMnYPK6fHlkoCOACIX0yqm2CqFNv/XT2rYJ2mFsXs4uDYV7QSDfqJ4fMyUQxsYzqQH/qBi2gP630+il7UmIA7Uddsfl6Wx8ugICX2frUTLNu6/B0a0hFiO++bw==
#    rsa-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo0BlgdQtsk6Zs66/ftJXWkCwFqzYzDRb7l60NNCWIYKiFsbPBpJxMg9i4a4ADPiecjcaMSNt+/+MRTwZ+QsD8zf/T6LM1uGEc1f9tCLTlKx/+sC/Sc5J2558/VpVBI6xyB8azXOU9k+gZ/jM2sxd4fgbh9KijO12mDYg3fM9Jy7try8MPuVO35rdqdGp2HL5BXaPrQVils+kNMDZvikQ13nr3jjf/F03VWo1uSLviHeUquAvLUiylpX1SMNpOkmxzepMRITF51vqsPV0iGUAhNimqvcVDUn4anyQZ2snRfLRfIu5JKyfJbaNTIKWYhHMaClHnl7H0+bIz35cTWcofwIDAQAB
#    rsa-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCjQGWB1C2yTpmzrr9+0ldaQLAWrNjMNFvuXrQ00JYhgqIWxs8GknEyD2LhrgAM+J5yNxoxI237/4xFPBn5CwPzN/9PoszW4YRzV/20ItOUrH/6wL9Jzknbnnz9WlUEjrHIHxrNc5T2T6Bn+MzazF3h+BuH0qKM7XaYNiDd8z0nLu2vLww+5U7fmt2p0anYcvkFdo+tBWKWz6Q0wNm+KRDXeeveON/8XTdVajW5Iu+Id5Sq4C8tSLKWlfVIw2k6SbHN6kxEhMXnW+qw9XSIZQCE2Kaq9xUNSfhqfJBnaydF8tF8i7kkrJ8lto1MgpZiEcxoKUeeXsfT5sjPflxNZyh/AgMBAAECggEAbNvDFDidJBofid6L2RB/qTIbeXNWuYxshN3nwpQYmE3YseFuKU67Zos1/5EcfYnHdhfiQkQC0hgMvBogo53By4xalgrUFrGYtaVGCrlyZuBEErw2kguZ2nWrmPGEYZ6ZU/3RzJA3E6vzJYGVcIz4SXc9PGurctfhzgvCDN5mt9oVgnHOU10GRvs0WYYtjc4IXvuhDeTbHLxiAQWEEVu4uPIN4QsjbeYnSHZV3np5uLeQ4AmmwoVmifvH8SWkVOeGy/5Nq37SlW0wbzFiQPjIaW2VI7BTlFk6yGpJ0eepHDJD1SOsIaOLUfyvolAX4iz5jKgfKohujE5McK8ZXft4aQKBgQDOnSRgHm/4Atn4gELRG5wkn2bp/S4fPsHvkrkLQ6K2UbCNT+aVlK83xQLQ/NHH9Zqoe2mDjdgZZtN0U4n37Y3WmtnmOe9zwiPrMqqlAC6mBknmkxzVvnv+HcF5wtDketYunfzUrfmdsPQ2CJyfdnq+iPlHiFHyBWvzK3iA36MrMwKBgQDKReIPbjEbiFZInvFypovMrYFSP5uxcP/z2xiSVFr7BxFgdY9DgQqWr1SX4H/ycMqN6MQpPBNfvalulnHOK0qYAVpCExARmEDfqiVtoBtaDcSWe3cEadugRrbYjBKGfTpKB9Si1bS9aZUCFA7FJ7MglZty2J6oWyAMhLnxcs9thQKBgQCSJxivIXjE8IdtwJUDREucoGF1TZINqiAXrytUa4CzBXAlVgrfbrDPe341hVGD6BmB6uLFm1XtCg60L8/d4F3AHAPdVsgqk39DBbEuTMWyzaoC/7ea/0bIiBXvYr7PkJDnovxRGcwEH0Nw4YChUHcdRtlHH4gP8oPdHLf+ObQ7fwKBgDbycu10JpzvFVlW7AoUGgf43heEtfum0bDhxLQDfE+S5PKKHOfehwzWBinXz4oBf9S69YaqDi1E7WDgN3wlIHdYbrdiTEwrSvw3UUGNa8Cz2sJyOauWQhYw/3yl2GZ2YD46EFZHrXiC1PqijjyagzuHyJmTJM5hKryb1ZM0eAqtAoGAXnPnD9Dri9+cTor16jKrCUH8PFMZ4TCFYRzWAr/+ayCylMdaxFjvVcaE+UJpyVw62FCgYV70Zqtsj1E4UGTp1lPM7RNudFw8FC9Pca95UYheCQc6/YMA1ACDR3hnnAUU0925T9/QhESCVQyEaFZVyBiPLZRygSWiIpAr6zKojDA=

#xxl任务
xxl:
  job:
    executor:
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: /data/applogs/xxl-job/jobhandler
      # 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
      appname: xxl-job-executor-sample
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      # 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
      logretentiondays: 15
      ip:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://127.0.0.1:9990/xxl-job-admin
    # 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: